version: '2'
services:
  vnsdinternal-app:
    image: vnsdinternal
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://vnsdinternal-postgresql:5432/vnsdinternal
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 18080:18080
  vnsdinternal-postgresql:
    extends:
      file: postgresql.yml
      service: vnsdinternal-postgresql
